#!/usr/bin/with-contenv sh

## Settings should be set
export PORT=9999

# Only support redis now. If redis is setup, then enable cache
export CACHE=redis
export CACHE_REDIS_ADDR=127.0.0.1:6379
export CACHE_REDIS_PASSWORD=
export CACHE_REDIS_DB=3

# Credential for internal communication
export BASIC_AUTH_USER=chart_controller
export BASIC_AUTH_PASS=86TObadymyLTGfjU

# Multiple tenants
# Must be set with 1 to support project namespace
export DEPTH=1

# Backend storage driver: e.g. "local", "amazon", "google" etc.
export STORAGE=local

# Storage driver settings
export STORAGE_LOCAL_ROOTDIR=/chart_storage

## Settings with default values. Just put here for future changes
export DEBUG=false
export LOG_JSON=true
export DISABLE_METRICS=false
export DISABLE_API=false
export DISABLE_STATEFILES=false
export ALLOW_OVERWRITE=true
export CHART_URL=
export AUTH_ANONYMOUS_GET=false
export TLS_CERT=
export TLS_KEY=
export CONTEXT_PATH=
export INDEX_LIMIT=0
export MAX_STORAGE_OBJECTS=0
export MAX_UPLOAD_SIZE=20971520
export CHART_POST_FORM_FIELD_NAME=chart
export PROV_POST_FORM_FIELD_NAME=prov


/wait-for-postgres.sh -- /usr/local/bin/chartm